### PR TITLE
README: Added talks for September and October meetup

### PR DESCRIPTION
**Pull request by tasdikrahman**
Updated the README to reflect the talks by speakers for the
- September
- October meetup

### CODE REVIEW

**Comment by shrayasr** [comment]
Thank you kind sir :)

**Comment by tasdikrahman** [comment]
@shrayasr My pleasure :smile: Any thing else which needs to be done? Will try my hand at it

**Comment by shrayasr** [comment]
> Any thing else which needs to be done? Will try my hand at it

Every month these are recurrent tasks so it would be awesome if you could handle it :)

**Comment by tasdikrahman** [comment]
@shrayasr Will do :+1:

**Comment by shrayasr** [comment]
Thank you :ok_hand: :+1:

**Pull request merged**
