### PR TITLE
Updated Chennaipy talks - readme.md file upto July 2016 talks

### PR DESCRIPTION
**Pull request by hazeez**
Shrayas,

I have updated the Chennaipy talks till the latest meetup talks. You may review once and merge with the master branch if all found OK. I have done a proof read once.

Thanks
Azeez

### CODE REVIEW

**Comment by kirang89** [comment]
That's quite some work! Thanks for doing this Hazeez 👍

**Comment by hazeez** [comment]
Don't mention it! It's high time I start contributing to this awesome
community.

**Comment by kirang89** [comment]
You should perhaps tag @shrayasr to get his attention :)

**Comment by kirang89** [comment]
Since there hasn't been any response from @shrayasr, I'll merge it in. We can fix issues if any in a seperate PR.

**Comment by hazeez** [comment]
Thanks @kirang89. You have been warm and welcoming all the way. @shrayasr
enjoying the long weekend?

**Comment by shrayasr** [comment]
WOW. @hazeez you are awesome :tada: :ok_hand: :tada: !!!

Yes, I was away :grin:

**Pull request merged**
